image: ruby:2.7-buster

before_script:
  - gem install bundler
  - bundle config set path vendor
  - bundle install

cache:
  paths:
    - vendor/

test:
  except: 
    - master
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test

pages:
  only: 
    - master
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
