name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
      - chore/gh-actions

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
